### ISSUE TITLE
Asana raises ForbiddenError when updating task status

### ISSUE THREAD

**Issue by soundofjw** [Loudr/asana-hub#45]
Asana raises `Exception: ForbiddenError(u'Forbidden: task: Not the correct type',)`.

I'm not exactly sure why asana might say a task isn't the "correct type," but my guess is a merged [duplicate] task.
## Traceback

``` python
Exception: ForbiddenError(u'Forbidden: task: Not the correct type',)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/asana_hub/tool.py", line 401, in __init__
    action.run()
  File "/Library/Python/2.7/site-packages/asana_hub/actions/sync.py", line 284, in run
    task = app.get_asana_task(task_id)
  File "/Library/Python/2.7/site-packages/asana_hub/tool.py", line 286, in get_asana_task
    return self.asana.tasks.find_by_id(asana_task_id)
  File "/Library/Python/2.7/site-packages/asana/resources/gen/tasks.py", line 49, in find_by_id
    return self.client.get(path, params, **options)
  File "/Library/Python/2.7/site-packages/asana/client.py", line 107, in get
    return self.request('get', path, params=query, **options)
  File "/Library/Python/2.7/site-packages/asana/client.py", line 77, in request
    raise STATUS_MAP[response.status_code](response)
ForbiddenError: Forbidden: task: Not the correct type
```
## Asana Tasks:
#42615939304807

**Comment by soundofjw** [comment]
This is back, likely introduced by multiprocessing changes in #48
