### ISSUE TITLE
invalid project id error handling

### ISSUE THREAD

**Issue by lordnynex** [Loudr/asana-hub#71]
I accidentally supplied a workspace ID instead of a project ID

This yields the following trace

``` python
Exception: TypeError('%d format: a number is required, not str',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/asana_hub/tool.py", line 446, in __init__
    action.run()
  File "/usr/local/lib/python2.7/dist-packages/asana_hub/actions/sync.py", line 107, in run
    repo, project = self.get_repo_and_project()
  File "/usr/local/lib/python2.7/dist-packages/asana_hub/action.py", line 81, in get_repo_and_project
    on_save=lambda p: p['id']
  File "/usr/local/lib/python2.7/dist-packages/asana_hub/json_data.py", line 95, in apply
    value = on_load(value)
  File "/usr/local/lib/python2.7/dist-packages/asana/resources/gen/projects.py", line 73, in find_by_id
    path = "/projects/%d" % (project)
TypeError: %d format: a number is required, not str
```

Further, this invalid ID is persisted to the .proj file which squelches the same trace on every run. 

To fix this I had to delete the .proj file and sync

**Comment by soundofjw** [comment]
Nice catch, there should be up front validation.
You can change the project ID via CLI with `--project`
